language: elixir
dist: trusty
addons:
  chrome: stable
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - npm install && node_modules/brunch/bin/brunch build --production
  - mix compile
  - mix phx.digest
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 20.3
  - 21.0
  - 22.0
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 21.0
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 20.3

env:
  - MIX_ENV=test

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - export TRAVIS=true
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - nohup chromedriver &
  - while sleep 5m; do echo "=====[ $SECONDS seconds, dialyzer still dialyzing... ]====="; done &

script: mix test && mix dialyzer --halt-exit-status

after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report

cache:
  directories:
    - _build
    - deps
